name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  ci:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Skip Test for HTML
        run: |
          echo "No package.json found. Skipping tests for Static HTML site"
          echo "Everything looks good!"
